name: On Release

on:
  release:
    types:
      - published

permissions:
  contents: read
  actions: read

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print tag
        run: |
          echo "Tag: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Repository: ${{ github.repository }}"
          echo "Triggered by: Release event"
