name: Semantic Release

on:
  push:
    branches: [master]

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.FULL_ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.FULL_ACCESS_TOKEN }}
        run: npx semantic-release
